{
  "openapi": "3.0.1",
  "info": {
    "title": "HRM",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:5000/api/v1"
    }
  ],
  "tags": [
    {
      "name": "User API"
    },
    {
      "name": "Form API"
    },
    {
      "name": "Account API"
    },
    {
      "name": "Role API"
    },
    {
      "name": "User Role API"
    },
    {
      "name": "Role Permission Form API"
    },
    {
      "name": "Module API"
    },
    {
      "name": "Report API"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "tags": [
          "User API"
        ],
        "summary": "Get All Users",
        "operationId": "GetAllUsers",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "description": "hr",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "User API"
        ],
        "summary": "Create New User and Account",
        "operationId": "CreateNewUserandAccount",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "required": [
                  "address",
                  "avatar",
                  "department",
                  "email",
                  "employee_code",
                  "firstname",
                  "identification_card",
                  "lastname",
                  "parent",
                  "password",
                  "phone",
                  "position",
                  "role_id",
                  "social_insurance"
                ],
                "properties": {
                  "employee_code": {
                    "type": "integer",
                    "description": "",
                    "format": "int32"
                  },
                  "firstname": {
                    "type": "string",
                    "description": ""
                  },
                  "lastname": {
                    "type": "string",
                    "description": ""
                  },
                  "email": {
                    "type": "string",
                    "description": ""
                  },
                  "password": {
                    "type": "string",
                    "description": ""
                  },
                  "phone": {
                    "type": "string",
                    "description": ""
                  },
                  "avatar": {
                    "type": "string",
                    "description": ""
                  },
                  "identification_card": {
                    "type": "integer",
                    "description": "",
                    "format": "int32"
                  },
                  "social_insurance": {
                    "type": "integer",
                    "description": "",
                    "format": "int32"
                  },
                  "address": {
                    "type": "string",
                    "description": ""
                  },
                  "department": {
                    "type": "string",
                    "description": ""
                  },
                  "parent": {
                    "type": "string",
                    "description": ""
                  },
                  "position": {
                    "type": "string",
                    "description": ""
                  },
                  "role_id": {
                    "type": "string",
                    "description": ""
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/users/e6f62dd3-5775-4b0f-93d1-76e43044e057": {
      "get": {
        "tags": [
          "User API"
        ],
        "summary": "Get User By ID",
        "operationId": "GetUserByID",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/users/f52da109-d7fd-4e20-8536-957da064a8f1": {
      "put": {
        "tags": [
          "User API"
        ],
        "summary": "Update User and Account Info",
        "operationId": "UpdateUserandAccountInfo",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "required": [
                  "address",
                  "avatar",
                  "department",
                  "email",
                  "employee_code",
                  "firstname",
                  "identification_card",
                  "lastname",
                  "parent",
                  "password",
                  "phone",
                  "position",
                  "role_id",
                  "social_insurance"
                ],
                "properties": {
                  "employee_code": {
                    "type": "string",
                    "description": ""
                  },
                  "firstname": {
                    "type": "string",
                    "description": ""
                  },
                  "lastname": {
                    "type": "string",
                    "description": ""
                  },
                  "email": {
                    "type": "string",
                    "description": ""
                  },
                  "phone": {
                    "type": "integer",
                    "description": "",
                    "format": "int32"
                  },
                  "avatar": {
                    "type": "string",
                    "description": ""
                  },
                  "identification_card": {
                    "type": "integer",
                    "description": "",
                    "format": "int32"
                  },
                  "social_insurance": {
                    "type": "integer",
                    "description": "",
                    "format": "int32"
                  },
                  "address": {
                    "type": "string",
                    "description": ""
                  },
                  "department": {
                    "type": "string",
                    "description": ""
                  },
                  "parent": {
                    "type": "string",
                    "description": ""
                  },
                  "position": {
                    "type": "string",
                    "description": ""
                  },
                  "password": {
                    "type": "string",
                    "description": ""
                  },
                  "role_id": {
                    "type": "string",
                    "description": ""
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      },
      "delete": {
        "tags": [
          "User API"
        ],
        "summary": "Delete User and Account",
        "operationId": "DeleteUserandAccount",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/login": {
      "post": {
        "tags": [
          "User API"
        ],
        "summary": "Login",
        "operationId": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/forms": {
      "get": {
        "tags": [
          "Form API"
        ],
        "summary": "Get All Forms",
        "operationId": "GetAllForms",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Form API"
        ],
        "summary": "Create New Form",
        "operationId": "CreateNewForm",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateNewFormRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      },
      "patch": {
        "tags": [
          "Form API"
        ],
        "summary": "Employee Update Form",
        "operationId": "EmployeeUpdateForm",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/forms/b7457fe1-afec-4849-a6c8-835474481855": {
      "get": {
        "tags": [
          "Form API"
        ],
        "summary": "Get Form By ID",
        "operationId": "GetFormByID",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": [
          "Form API"
        ],
        "summary": "Manager - Approve Form",
        "operationId": "Manager-ApproveForm",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Manager-ApproveFormRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      },
      "patch": {
        "tags": [
          "Form API"
        ],
        "summary": "User - Update Form",
        "operationId": "User-UpdateForm",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User-UpdateFormRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/forms/6691f93e-9b4c-455e-9442-d5fc513e4294": {
      "delete": {
        "tags": [
          "Form API"
        ],
        "summary": "Delete Form",
        "operationId": "DeleteForm",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/form-approve/d4d72685-384b-4998-8fcf-8abcc4ecb2bc": {
      "patch": {
        "tags": [
          "Form API"
        ],
        "summary": "Approve Form",
        "operationId": "ApproveForm",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ApproveFormRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/accounts/79781226-62bb-421a-8621-0aa132e58064": {
      "delete": {
        "tags": [
          "Account API"
        ],
        "summary": "Delete Account",
        "operationId": "DeleteAccount",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/accounts": {
      "get": {
        "tags": [
          "Account API"
        ],
        "summary": "Get All User Accounts",
        "operationId": "GetAllUserAccounts",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/accounts/607eebc7-72a4-4541-aa95-2f3277e42175": {
      "get": {
        "tags": [
          "Account API"
        ],
        "summary": "Get User Account By ID",
        "operationId": "GetUserAccountByID",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": [
          "Account API"
        ],
        "summary": "Update User Account",
        "operationId": "UpdateUserAccount",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserAccountRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/roles": {
      "get": {
        "tags": [
          "Role API"
        ],
        "summary": "Get All Roles",
        "operationId": "GetAllRoles",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Role API"
        ],
        "summary": "Create New Role",
        "operationId": "CreateNewRole",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateNewRoleRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/roles/ffc8c623-ee2f-48e7-9f7c-42edad317a69": {
      "get": {
        "tags": [
          "Role API"
        ],
        "summary": "Get Role By ID",
        "operationId": "GetRoleByID",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": [
          "Role API"
        ],
        "summary": "Update Role",
        "operationId": "UpdateRole",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRoleRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/roles/8409a9b1-3e99-4abc-9940-52d8c116d6ec": {
      "delete": {
        "tags": [
          "Role API"
        ],
        "summary": "Delete Role",
        "operationId": "DeleteRole",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/user-role": {
      "post": {
        "tags": [
          "User Role API"
        ],
        "summary": "Create New User Role",
        "operationId": "CreateNewUserRole",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateNewUserRoleRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/user-roles": {
      "get": {
        "tags": [
          "User Role API"
        ],
        "summary": "Get All User Roles",
        "operationId": "GetAllUserRoles",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "description": "admin",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/user-role/684eeb16-4c9e-4e79-9913-2ccf3deae9e4": {
      "get": {
        "tags": [
          "User Role API"
        ],
        "summary": "Get User Role By ID",
        "operationId": "GetUserRoleByID",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/user-role/efa541d9-12ca-4e7c-8d64-f210375ff45b": {
      "put": {
        "tags": [
          "User Role API"
        ],
        "summary": "Update User Role",
        "operationId": "UpdateUserRole",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRoleRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/user-roles/aca58357-34c2-44d6-930e-dd2b0f1215d3": {
      "delete": {
        "tags": [
          "User Role API"
        ],
        "summary": "Delete User Role",
        "operationId": "DeleteUserRole",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "description": "admin",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/permissions": {
      "get": {
        "tags": [
          "Role Permission Form API"
        ],
        "summary": "Get All Role Permission Form",
        "operationId": "GetAllRolePermissionForm",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      },
      "post": {
        "tags": [
          "Role Permission Form API"
        ],
        "summary": "Create New Role Permission Form",
        "operationId": "CreateNewRolePermissionForm",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateNewRolePermissionFormRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/permissions/b54b1a75-d7b3-4791-869e-5d5605bce1e1": {
      "patch": {
        "tags": [
          "Role Permission Form API"
        ],
        "summary": "Update Role Permission Form",
        "operationId": "UpdateRolePermissionForm",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRolePermissionFormRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/permissions/63d9c105-1718-461c-be23-09423ec0fd13": {
      "delete": {
        "tags": [
          "Role Permission Form API"
        ],
        "summary": "Delete Role Permission Form",
        "operationId": "DeleteRolePermissionForm",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/modules": {
      "post": {
        "tags": [
          "Module API"
        ],
        "summary": "Create New Module",
        "operationId": "CreateNewModule",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "description": "admin",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateNewModuleRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/modules/8dd504a7-c244-48e3-a9cc-09f90fbc0da3": {
      "put": {
        "tags": [
          "Module API"
        ],
        "summary": "Update Module",
        "operationId": "UpdateModule",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateModuleRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false,
        "x-codegen-request-body-name": "Body"
      }
    },
    "/": {
      "get": {
        "tags": [
          "Module API"
        ],
        "summary": "Delete Modules",
        "operationId": "DeleteModules",
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/reports/forms": {
      "get": {
        "tags": [
          "Report API"
        ],
        "summary": "Get All Reports",
        "operationId": "GetAllReports",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/reports-manager/forms": {
      "get": {
        "tags": [
          "Report API"
        ],
        "summary": "Get All Manager Reports",
        "operationId": "GetAllManagerReports",
        "parameters": [
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    },
    "/reports-status/forms": {
      "get": {
        "tags": [
          "Report API"
        ],
        "summary": "Get All Report By Status",
        "operationId": "GetAllReportByStatus",
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "jwt",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "LoginRequest": {
        "title": "LoginRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "huongntt@vmodev.com",
          "password": "huongntt"
        }
      },
      "CreateNewFormRequest": {
        "title": "CreateNewFormRequest",
        "required": [
          "form_type",
          "hr_review",
          "status",
          "user_id"
        ],
        "type": "object",
        "properties": {
          "user_id": {
            "type": "string"
          },
          "form_type": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "hr_review": {
            "type": "string"
          }
        },
        "example": {
          "user_id": "5984b4cb-841e-4897-b3a0-2dbe71f21f26",
          "form_type": "1",
          "status": "submitted",
          "hr_review": "Test Form 1"
        }
      },
      "User-UpdateFormRequest": {
        "title": "User-UpdateFormRequest",
        "required": [
          "archivement",
          "manager",
          "personal_review",
          "status",
          "task"
        ],
        "type": "object",
        "properties": {
          "manager": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "personal_review": {
            "type": "string"
          },
          "task": {
            "type": "string"
          },
          "archivement": {
            "type": "string"
          }
        },
        "example": {
          "manager": "5bba59cc-30e3-430d-934d-522fb72c0d81",
          "status": "pending approve",
          "personal_review": "Excellent",
          "task": "HRM SYS",
          "archivement": "HRM SYS"
        }
      },
      "Manager-ApproveFormRequest": {
        "title": "Manager-ApproveFormRequest",
        "required": [
          "manager_review",
          "status"
        ],
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "manager_review": {
            "type": "string"
          }
        },
        "example": {
          "status": "approved",
          "manager_review": "Awesome"
        }
      },
      "ApproveFormRequest": {
        "title": "ApproveFormRequest",
        "required": [
          "manager_review",
          "status"
        ],
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "manager_review": {
            "type": "string"
          }
        },
        "example": {
          "status": "approved",
          "manager_review": "Good Chop"
        }
      },
      "UpdateUserAccountRequest": {
        "title": "UpdateUserAccountRequest",
        "required": [
          "email",
          "password",
          "user_id"
        ],
        "type": "object",
        "properties": {
          "user_id": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "user_id": "b6e75566-e457-4f16-9bba-a1929fb153dd",
          "email": "ducbla9999@gmail.com",
          "password": "ducbla"
        }
      },
      "CreateNewRoleRequest": {
        "title": "CreateNewRoleRequest",
        "required": [
          "role_name"
        ],
        "type": "object",
        "properties": {
          "role_name": {
            "type": "string"
          }
        },
        "example": {
          "role_name": "employee"
        }
      },
      "UpdateRoleRequest": {
        "title": "UpdateRoleRequest",
        "required": [
          "createBy",
          "updateBy"
        ],
        "type": "object",
        "properties": {
          "createBy": {
            "type": "string"
          },
          "updateBy": {
            "type": "string"
          }
        },
        "example": {
          "createBy": "2d4683cd-37ae-4952-af63-da027f8cc6af",
          "updateBy": "2d4683cd-37ae-4952-af63-da027f8cc6af"
        }
      },
      "CreateNewUserRoleRequest": {
        "title": "CreateNewUserRoleRequest",
        "required": [
          "createBy",
          "role_id",
          "updateBy",
          "user_id"
        ],
        "type": "object",
        "properties": {
          "role_id": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          },
          "createBy": {
            "type": "string"
          },
          "updateBy": {
            "type": "string"
          }
        },
        "example": {
          "role_id": "ffc8c623-ee2f-48e7-9f7c-42edad317a69",
          "user_id": "e6f62dd3-5775-4b0f-93d1-76e43044e057",
          "createBy": "2d4683cd-37ae-4952-af63-da027f8cc6af",
          "updateBy": "2d4683cd-37ae-4952-af63-da027f8cc6af"
        }
      },
      "UpdateUserRoleRequest": {
        "title": "UpdateUserRoleRequest",
        "required": [
          "createBy",
          "updateBy"
        ],
        "type": "object",
        "properties": {
          "createBy": {
            "type": "string"
          },
          "updateBy": {
            "type": "string"
          }
        },
        "example": {
          "createBy": "2d4683cd-37ae-4952-af63-da027f8cc6af",
          "updateBy": "2d4683cd-37ae-4952-af63-da027f8cc6af"
        }
      },
      "CreateNewRolePermissionFormRequest": {
        "title": "CreateNewRolePermissionFormRequest",
        "required": [
          "canApprove",
          "canCreate",
          "canDelete",
          "canRead",
          "canUpdate",
          "createBy",
          "module_id",
          "role_id",
          "updateBy",
          "url"
        ],
        "type": "object",
        "properties": {
          "role_id": {
            "type": "string"
          },
          "module_id": {
            "type": "string"
          },
          "canCreate": {
            "type": "string"
          },
          "canRead": {
            "type": "string"
          },
          "canUpdate": {
            "type": "string"
          },
          "canDelete": {
            "type": "string"
          },
          "canApprove": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "createBy": {
            "type": "string"
          },
          "updateBy": {
            "type": "string"
          }
        },
        "example": {
          "role_id": "ffc8c623-ee2f-48e7-9f7c-42edad317a69",
          "module_id": "3a50a4d0-1815-4bdf-b590-558b3533f6eb",
          "canCreate": "1",
          "canRead": "1",
          "canUpdate": "1",
          "canDelete": "1",
          "canApprove": "1",
          "url": "/users",
          "createBy": "2d4683cd-37ae-4952-af63-da027f8cc6af",
          "updateBy": "2d4683cd-37ae-4952-af63-da027f8cc6af"
        }
      },
      "UpdateRolePermissionFormRequest": {
        "title": "UpdateRolePermissionFormRequest",
        "required": [
          "createBy",
          "updateBy"
        ],
        "type": "object",
        "properties": {
          "createBy": {
            "type": "string"
          },
          "updateBy": {
            "type": "string"
          }
        },
        "example": {
          "createBy": "2d4683cd-37ae-4952-af63-da027f8cc6af",
          "updateBy": "2d4683cd-37ae-4952-af63-da027f8cc6af"
        }
      },
      "CreateNewModuleRequest": {
        "title": "CreateNewModuleRequest",
        "required": [
          "module_name"
        ],
        "type": "object",
        "properties": {
          "module_name": {
            "type": "string"
          }
        },
        "example": {
          "module_name": "permissions"
        }
      },
      "UpdateModuleRequest": {
        "title": "UpdateModuleRequest",
        "required": [
          "createBy",
          "updateBy"
        ],
        "type": "object",
        "properties": {
          "createBy": {
            "type": "string"
          },
          "updateBy": {
            "type": "string"
          }
        },
        "example": {
          "createBy": "2d4683cd-37ae-4952-af63-da027f8cc6af",
          "updateBy": "2d4683cd-37ae-4952-af63-da027f8cc6af"
        }
      }
    }
  }
}